# Generated by Django 2.2.2 on 2019-08-29 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTypesClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва типу гуртка')),
            ],
            options={
                'verbose_name': 'Тип діяльності гуртків',
                'verbose_name_plural': 'Типи діяльності гуртків',
            },
        ),
        migrations.CreateModel(
            name='ContentTypesLegals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва типу документа')),
            ],
            options={
                'verbose_name': 'Тип документів',
                'verbose_name_plural': 'Типи документів',
            },
        ),
        migrations.CreateModel(
            name='ContentTypesNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва типу новини')),
            ],
            options={
                'verbose_name': 'Тип новин',
                'verbose_name_plural': 'Типи новин',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва події')),
                ('date_placing', models.DateTimeField(default=datetime.datetime(2019, 8, 29, 18, 59, 53, 483401, tzinfo=utc), verbose_name='Дата проходження події')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/event_detail/', verbose_name='Документ з детальною інформацією')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва курсу')),
                ('description', models.TextField(blank=True, help_text='Введіть основну інформацію про курс', max_length=5000, verbose_name='Опис діяльності підготовчого курсу')),
                ('image', models.ImageField(default='default/default_image_training_courses.png', upload_to='image/training_course_image/', verbose_name='Емблема або інше характерне зображення')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/training_course_detail/', verbose_name='Документ з детальою інформацією')),
            ],
            options={
                'verbose_name': 'Підготовчий курс',
                'verbose_name_plural': 'Підготовчі курси',
            },
        ),
        migrations.CreateModel(
            name='TypesRelationContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва типу контакта')),
            ],
            options={
                'verbose_name': 'Тип контактів',
                'verbose_name_plural': 'Типи контактів',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок новини')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Опис новини')),
                ('image', models.ImageField(default='default/default_image_news.png', upload_to='image/new_image', verbose_name='Основне зображення новини')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/new_detail/', verbose_name='Документ з детальною інформацією')),
                ('visitors_type', models.CharField(choices=[('p', 'Батьки'), ('s', 'Студенти'), ('w', 'Працівники'), ('f', 'Партнери')], default='s', max_length=1, verbose_name='Тип користувача')),
                ('content_types', models.ManyToManyField(default='Загальний', related_name='content_type', to='public.ContentTypesNews', verbose_name='Тип новини')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.CreateModel(
            name='Legals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва документа')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/legal_detail/', verbose_name='Документ з детальою інформацією')),
                ('content_type', models.ForeignKey(on_delete=models.SET('Документ'), to='public.ContentTypesLegals', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Назва кантакту')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зміст контакту')),
                ('type_relation', models.ForeignKey(on_delete=models.SET('Контакт'), to='public.TypesRelationContacts', verbose_name='Тип контакту')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва гуртка')),
                ('description', models.TextField(blank=True, help_text='Введіть основну інформацію про гурток', max_length=5000, verbose_name='Опис діяльності гуртка')),
                ('image', models.ImageField(default='default/default_image_clubs.png', upload_to='image/club_image/', verbose_name='Емблема або інше характерне зображення')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/club_detail/', verbose_name='Документ з детальою інформацією')),
                ('season_set', models.CharField(choices=[('a', 'Весь рік'), ('e', 'Академічний рік'), ('s', 'Літні канікули')], max_length=1, verbose_name='Час активності')),
                ('members_age', models.CharField(choices=[('p', 'Учні'), ('s', 'Студенти'), ('c', 'Учні/Студенти')], default='c', max_length=1, verbose_name='Вік відвідувачів гуртка')),
                ('activity_type', models.ForeignKey(on_delete=models.SET('Навчальний'), to='public.ActivityTypesClubs', verbose_name='Напрямок діяльності гуртка')),
            ],
            options={
                'verbose_name': 'Гурток',
                'verbose_name_plural': 'Гуртки',
            },
        ),
    ]
