# Generated by Django 2.2.2 on 2019-09-03 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='image',
            field=models.ImageField(default='default/default_image_club.png', upload_to='image/club_image/', verbose_name='Емблема або інше характерне зображення'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_placing',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 18, 23, 14, 38533, tzinfo=utc), verbose_name='Дата проходження події'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_types',
            field=models.ManyToManyField(default='Загальний', related_name='news', to='public.ContentTypesNews', verbose_name='Тип новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default/default_image_new.png', upload_to='image/new_image', verbose_name='Основне зображення новини'),
        ),
        migrations.AlterField(
            model_name='trainingcourses',
            name='image',
            field=models.ImageField(default='default/default_image_training_course.png', upload_to='image/training_course_image/', verbose_name='Емблема або інше характерне зображення'),
        ),
    ]
