# Generated by Django 2.2.2 on 2019-09-29 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20190903_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={'ordering': ['name'], 'verbose_name': 'Гурток', 'verbose_name_plural': 'Гуртки'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['label'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['date_placing'], 'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
        migrations.AlterModelOptions(
            name='legals',
            options={'ordering': ['name'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['post_date'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='trainingcourses',
            options={'ordering': ['name'], 'verbose_name': 'Підготовчий курс', 'verbose_name_plural': 'Підготовчі курси'},
        ),
        migrations.AlterField(
            model_name='events',
            name='date_placing',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 13, 2, 56, 297990, tzinfo=utc), verbose_name='Дата проходження події'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_types',
            field=models.ManyToManyField(default='Загальний', related_name='news', to='public.ContentTypesNews', verbose_name='Типи новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='post_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публікації'),
        ),
    ]
