# Generated by Django 2.2.2 on 2019-09-29 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20190929_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_placing',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проходження події'),
        ),
    ]
