# Generated by Django 2.2.2 on 2019-10-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20190929_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
