# Generated by Django 2.2.2 on 2019-10-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20191007_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-date_placing'], 'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
    ]
